default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "shugo_system_db") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "shugo_system_db") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "shugo_system_db") %>
